-------------------------------------------------------------------------------
--  EllesmereUI_BulshackPreset.lua
--  Built-in "Bulshack" profile preset. Injected into EllesmereUIDB on first
--  load so new users can select it from the Profiles menu.
--  Auto-generated from Bulshackx's live SavedVariables.
-------------------------------------------------------------------------------
local PRESET_NAME = "Bulshack"

-- Wait for SavedVariables to be available, then inject the preset
local loader = CreateFrame("Frame")
loader:RegisterEvent("ADDON_LOADED")
loader:SetScript("OnEvent", function(self, event, addon)
    if addon ~= "EllesmereUI" then return end
    self:UnregisterEvent("ADDON_LOADED")

    -- Only inject if the profile doesn't already exist (don't overwrite user edits)
    EllesmereUIDB = EllesmereUIDB or {}
    EllesmereUIDB.profiles = EllesmereUIDB.profiles or {}

    if EllesmereUIDB.profiles[PRESET_NAME] then return end

    EllesmereUIDB.profiles[PRESET_NAME] = {
["fonts"] = {
["global"] = "Expressway",
["outlineMode"] = "none",
},
["addons"] = {
["EllesmereUIActionBars"] = {
["pushedCustomColor"] = {
["a"] = 1,
["r"] = 0.01692232361440693,
["g"] = 0.8585884301153518,
["b"] = 1,
},
["procGlowColor"] = {
["r"] = 0.01692232361440693,
["g"] = 0.8585884301153518,
["b"] = 1,
},
["cooldownEdgeUseClassColor"] = true,
["pushedBorderSize"] = 4,
["highlightTextureType"] = 2,
["barPositions"] = {
["Bar3"] = {
["y"] = -468.5128205128205,
["relPoint"] = "CENTER",
["point"] = "CENTER",
["x"] = -171.4871794871795,
},
["Bar6"] = {
["y"] = -468.512837697769,
["relPoint"] = "CENTER",
["point"] = "CENTER",
["x"] = 338.8718073015387,
},
["QueueStatus"] = {
["y"] = -522.6666666666666,
["relPoint"] = "CENTER",
["point"] = "CENTER",
["x"] = -471.7948717948718,
},
["Bar8"] = {
["y"] = 248.6153846153846,
["relPoint"] = "CENTER",
["point"] = "CENTER",
["x"] = -355.2820512820513,
},
["XPBar"] = {
["y"] = -580.1025641025641,
["relPoint"] = "CENTER",
["point"] = "CENTER",
["x"] = 13.12820512820513,
},
["EncounterBar"] = {
["y"] = -276.5128205128205,
["relPoint"] = "CENTER",
["point"] = "CENTER",
["x"] = 638.3589743589744,
},
["PetBar"] = {
["y"] = 585.025641025641,
["relPoint"] = "CENTER",
["point"] = "CENTER",
["x"] = -907.4871794871794,
},
["Bar2"] = {
["y"] = -468.512837697769,
["relPoint"] = "CENTER",
["point"] = "CENTER",
["x"] = 169.0256472254648,
},
["VehicleExit"] = {
["y"] = -342.974358974359,
["relPoint"] = "CENTER",
["point"] = "CENTER",
["x"] = -180.5128205128205,
},
["Bar5"] = {
["y"] = -468.512837697769,
["relPoint"] = "CENTER",
["point"] = "CENTER",
["x"] = -338.8718073015387,
},
["MainBar"] = {
["y"] = -468.5128205128205,
["relPoint"] = "CENTER",
["point"] = "CENTER",
["x"] = 0,
},
["RepBar"] = {
["y"] = -562.8717948717948,
["relPoint"] = "CENTER",
["point"] = "CENTER",
["x"] = 13.94871794871795,
},
["Bar7"] = {
["y"] = 306.8717948717949,
["relPoint"] = "CENTER",
["point"] = "CENTER",
["x"] = -355.2820512820513,
},
["ExtraActionButton"] = {
["y"] = -88.61538461538461,
["relPoint"] = "CENTER",
["point"] = "CENTER",
["x"] = 585.8461538461538,
},
["MicroBar"] = {
["y"] = -522.6666666666666,
["relPoint"] = "CENTER",
["point"] = "CENTER",
["x"] = -643.2820512820513,
},
["StanceBar"] = {
["y"] = 585.025641025641,
["relPoint"] = "CENTER",
["point"] = "CENTER",
["x"] = -907.4871794871794,
},
["BagBar"] = {
["y"] = -563.6923076923076,
["relPoint"] = "CENTER",
["point"] = "CENTER",
["x"] = 456.2051282051282,
},
["Bar4"] = {
["y"] = -196.5128479003906,
["relPoint"] = "CENTER",
["point"] = "CENTER",
["x"] = 92.30770111083984,
},
},
["procGlowUseClassColor"] = true,
["procGlowScale"] = 1,
["highlightBorderSize"] = 4,
["useBlizzardDataBars"] = false,
["hideCastingAnimations"] = false,
["squareIcons"] = true,
["pushedUseClassColor"] = true,
["procGlowType"] = 0,
["pushedTextureType"] = 3,
["selectedBar"] = "Bar4",
["highlightUseClassColor"] = true,
["iconZoom"] = 5.5,
["cooldownEdgeColor"] = {
["a"] = 1,
["r"] = 0.01692232361440693,
["g"] = 0.8585884301153518,
["b"] = 1,
},
["highlightCustomColor"] = {
["a"] = 1,
["r"] = 0.01692232361440693,
["g"] = 0.8585884301153518,
["b"] = 1,
},
["bars"] = {
["Bar3"] = {
["visOnlyInstances"] = false,
["borderThickness"] = "thin",
["combatShowEnabled"] = false,
["targetWidth"] = 0,
["bgEnabled"] = true,
["numRows"] = 1,
["buttonHeight"] = 40,
["countFontColor"] = {
["b"] = 1,
["g"] = 1,
["r"] = 1,
},
["hideMacroText"] = false,
["borderColor"] = {
["a"] = 1,
["r"] = 0.8671813355546275,
["g"] = 0.9462819379697465,
["b"] = 0.01989737278717385,
},
["clickThrough"] = false,
["keybindOffsetX"] = 0,
["enabled"] = true,
["bgPadX"] = 0,
["disableTooltips"] = false,
["alwaysHidden"] = false,
["outOfRangeColoring"] = true,
["buttonPadding"] = 0,
["visHideHousing"] = false,
["barVisibility"] = "always",
["keybindFontColor"] = {
["b"] = 1,
["g"] = 1,
["r"] = 1,
},
["cooldownFontSize"] = 12,
["showPagingArrows"] = false,
["cooldownTextXOffset"] = 0,
["buttonWidth"] = 40,
["cooldownTextColor"] = {
["b"] = 1,
["g"] = 1,
["r"] = 1,
},
["housingHideEnabled"] = false,
["overrideNumRows"] = 3,
["borderSize"] = 1,
["keybindFontSize"] = 12,
["hideKeybind"] = false,
["countFontSize"] = 12,
["visHideMounted"] = false,
["bgPadY"] = 0,
["macroOffsetX"] = 0,
["visHideNoTarget"] = false,
["macroOffsetY"] = 0,
["macroFontSize"] = 12,
["cooldownTextYOffset"] = 0,
["bgColor"] = {
["a"] = 0.5,
["b"] = 0,
["g"] = 0,
["r"] = 0,
},
["mouseoverAlpha"] = 1,
["shapeBorderColor"] = {
["a"] = 1,
["r"] = 0.8671813355546275,
["g"] = 0.9462819379697465,
["b"] = 0.01989737278717385,
},
["growDirection"] = "up",
["combatHideEnabled"] = false,
["shapeBorderEnabled"] = true,
["outOfRangeColor"] = {
["b"] = 0.1,
["g"] = 0.1,
["r"] = 0.8,
},
["borderEnabled"] = true,
["numIcons"] = 12,
["countOffsetX"] = 0,
["pagingArrowsRight"] = false,
["macroFontColor"] = {
["b"] = 1,
["g"] = 1,
["r"] = 1,
},
["keybindOffsetY"] = 0,
["shapeBorderSize"] = 7,
["mouseoverEnabled"] = false,
["overrideNumIcons"] = 12,
["borderClassColor"] = false,
["alwaysShowButtons"] = true,
["targetHeight"] = 0,
["buttonShape"] = "none",
["orientation"] = "horizontal",
["mouseoverSpeed"] = 0.15,
["visHideNoEnemy"] = false,
["countOffsetY"] = 0,
},
["Bar6"] = {
["visOnlyInstances"] = false,
["borderThickness"] = "thin",
["combatShowEnabled"] = false,
["targetWidth"] = 0,
["bgEnabled"] = true,
["numRows"] = 1,
["buttonPadding"] = 0,
["countFontColor"] = {
["b"] = 1,
["g"] = 1,
["r"] = 1,
},
["buttonHeight"] = 40,
["borderColor"] = {
["a"] = 1,
["b"] = 0,
["g"] = 0,
["r"] = 0,
},
["hideMacroText"] = false,
["keybindOffsetX"] = 0,
["alwaysHidden"] = false,
["bgPadX"] = 0,
["disableTooltips"] = false,
["enabled"] = true,
["outOfRangeColoring"] = true,
["visHideHousing"] = false,
["showPagingArrows"] = false,
["targetHeight"] = 0,
["keybindFontColor"] = {
["b"] = 1,
["g"] = 1,
["r"] = 1,
},
["cooldownFontSize"] = 12,
["buttonShape"] = "none",
["cooldownTextXOffset"] = 0,
["buttonWidth"] = 40,
["cooldownTextColor"] = {
["b"] = 1,
["g"] = 1,
["r"] = 1,
},
["housingHideEnabled"] = false,
["overrideNumRows"] = 3,
["borderSize"] = 1,
["keybindFontSize"] = 12,
["hideKeybind"] = false,
["countFontSize"] = 12,
["visHideMounted"] = false,
["bgPadY"] = 0,
["macroOffsetX"] = 0,
["visHideNoTarget"] = false,
["macroOffsetY"] = 0,
["macroFontSize"] = 12,
["countOffsetX"] = 0,
["bgColor"] = {
["a"] = 0.5,
["b"] = 0,
["g"] = 0,
["r"] = 0,
},
["mouseoverAlpha"] = 1,
["shapeBorderColor"] = {
["a"] = 1,
["b"] = 0,
["g"] = 0,
["r"] = 0,
},
["growDirection"] = "up",
["combatHideEnabled"] = false,
["shapeBorderEnabled"] = true,
["outOfRangeColor"] = {
["b"] = 0.1,
["g"] = 0.1,
["r"] = 0.8,
},
["borderEnabled"] = true,
["numIcons"] = 12,
["mouseoverEnabled"] = false,
["pagingArrowsRight"] = false,
["macroFontColor"] = {
["b"] = 1,
["g"] = 1,
["r"] = 1,
},
["keybindOffsetY"] = 0,
["shapeBorderSize"] = 7,
["cooldownTextYOffset"] = 0,
["overrideNumIcons"] = 12,
["borderClassColor"] = true,
["alwaysShowButtons"] = true,
["barVisibility"] = "always",
["clickThrough"] = false,
["orientation"] = "horizontal",
["mouseoverSpeed"] = 0.15,
["visHideNoEnemy"] = false,
["countOffsetY"] = 0,
},
["ExtraActionButton"] = {
["alwaysHidden"] = false,
["mouseoverEnabled"] = false,
["combatShowEnabled"] = false,
["housingHideEnabled"] = false,
["combatHideEnabled"] = false,
["mouseoverSpeed"] = 0.15,
["clickThrough"] = false,
["mouseoverAlpha"] = 1,
},
["Bar8"] = {
["countOffsetY"] = 0,
["borderThickness"] = "thin",
["combatShowEnabled"] = false,
["targetWidth"] = 0,
["buttonHeight"] = 40,
["numRows"] = 1,
["buttonPadding"] = 0,
["countFontColor"] = {
["b"] = 1,
["g"] = 1,
["r"] = 1,
},
["visOnlyInstances"] = false,
["bgEnabled"] = true,
["borderColor"] = {
["a"] = 1,
["b"] = 0,
["g"] = 0,
["r"] = 0,
},
["keybindOffsetX"] = 0,
["alwaysHidden"] = true,
["bgPadX"] = 0,
["disableTooltips"] = false,
["enabled"] = true,
["outOfRangeColoring"] = true,
["barVisibility"] = "never",
["buttonShape"] = "none",
["targetHeight"] = 0,
["keybindFontColor"] = {
["b"] = 1,
["g"] = 1,
["r"] = 1,
},
["cooldownFontSize"] = 12,
["visHideHousing"] = false,
["cooldownTextXOffset"] = 0,
["overrideNumIcons"] = 12,
["overrideNumRows"] = 3,
["housingHideEnabled"] = false,
["cooldownTextColor"] = {
["b"] = 1,
["g"] = 1,
["r"] = 1,
},
["borderEnabled"] = true,
["keybindFontSize"] = 12,
["hideKeybind"] = false,
["countFontSize"] = 12,
["visHideMounted"] = false,
["bgPadY"] = 0,
["macroOffsetX"] = 0,
["visHideNoTarget"] = false,
["macroOffsetY"] = 0,
["macroFontSize"] = 12,
["cooldownTextYOffset"] = 0,
["bgColor"] = {
["a"] = 0.5,
["b"] = 0,
["g"] = 0,
["r"] = 0,
},
["borderSize"] = 1,
["shapeBorderColor"] = {
["a"] = 1,
["b"] = 0,
["g"] = 0,
["r"] = 0,
},
["growDirection"] = "up",
["clickThrough"] = false,
["shapeBorderEnabled"] = true,
["combatHideEnabled"] = false,
["outOfRangeColor"] = {
["b"] = 0.1,
["g"] = 0.1,
["r"] = 0.8,
},
["numIcons"] = 12,
["countOffsetX"] = 0,
["pagingArrowsRight"] = false,
["macroFontColor"] = {
["b"] = 1,
["g"] = 1,
["r"] = 1,
},
["keybindOffsetY"] = 0,
["shapeBorderSize"] = 7,
["mouseoverEnabled"] = false,
["buttonWidth"] = 40,
["borderClassColor"] = true,
["alwaysShowButtons"] = true,
["mouseoverAlpha"] = 1,
["showPagingArrows"] = false,
["orientation"] = "horizontal",
["mouseoverSpeed"] = 0.15,
["hideMacroText"] = false,
["visHideNoEnemy"] = false,
},
["XPBar"] = {
["alwaysHidden"] = false,
["mouseoverEnabled"] = false,
["combatShowEnabled"] = false,
["combatHideEnabled"] = false,
["width"] = 400,
["mouseoverAlpha"] = 1,
["barVisibility"] = "always",
["housingHideEnabled"] = false,
["height"] = 18,
["mouseoverSpeed"] = 0.15,
["orientation"] = "HORIZONTAL",
["clickThrough"] = true,
},
["EncounterBar"] = {
["alwaysHidden"] = false,
["mouseoverEnabled"] = false,
["combatShowEnabled"] = false,
["housingHideEnabled"] = false,
["combatHideEnabled"] = false,
["mouseoverSpeed"] = 0.15,
["clickThrough"] = false,
["mouseoverAlpha"] = 1,
},
["PetBar"] = {
["countOffsetY"] = 0,
["borderThickness"] = "thin",
["combatShowEnabled"] = false,
["targetWidth"] = 0,
["buttonHeight"] = 40,
["numRows"] = 1,
["buttonPadding"] = 0,
["countFontColor"] = {
["b"] = 1,
["g"] = 1,
["r"] = 1,
},
["visOnlyInstances"] = false,
["bgEnabled"] = true,
["borderColor"] = {
["a"] = 1,
["b"] = 0,
["g"] = 0,
["r"] = 0,
},
["keybindOffsetX"] = 0,
["alwaysHidden"] = true,
["bgPadX"] = 0,
["disableTooltips"] = false,
["enabled"] = true,
["outOfRangeColoring"] = true,
["barVisibility"] = "never",
["buttonShape"] = "none",
["targetHeight"] = 0,
["keybindFontColor"] = {
["b"] = 1,
["g"] = 1,
["r"] = 1,
},
["cooldownFontSize"] = 12,
["visHideHousing"] = false,
["cooldownTextXOffset"] = 0,
["overrideNumIcons"] = 12,
["overrideNumRows"] = 3,
["housingHideEnabled"] = false,
["cooldownTextColor"] = {
["b"] = 1,
["g"] = 1,
["r"] = 1,
},
["borderEnabled"] = true,
["keybindFontSize"] = 12,
["hideKeybind"] = false,
["countFontSize"] = 12,
["visHideMounted"] = false,
["bgPadY"] = 0,
["macroOffsetX"] = 0,
["visHideNoTarget"] = false,
["macroOffsetY"] = 0,
["macroFontSize"] = 12,
["cooldownTextYOffset"] = 0,
["bgColor"] = {
["a"] = 0.5,
["b"] = 0,
["g"] = 0,
["r"] = 0,
},
["borderSize"] = 1,
["shapeBorderColor"] = {
["a"] = 1,
["b"] = 0,
["g"] = 0,
["r"] = 0,
},
["growDirection"] = "up",
["clickThrough"] = false,
["shapeBorderEnabled"] = true,
["combatHideEnabled"] = false,
["outOfRangeColor"] = {
["b"] = 0.1,
["g"] = 0.1,
["r"] = 0.8,
},
["numIcons"] = 12,
["countOffsetX"] = 0,
["pagingArrowsRight"] = false,
["macroFontColor"] = {
["b"] = 1,
["g"] = 1,
["r"] = 1,
},
["keybindOffsetY"] = 0,
["shapeBorderSize"] = 7,
["mouseoverEnabled"] = false,
["buttonWidth"] = 40,
["borderClassColor"] = true,
["alwaysShowButtons"] = true,
["mouseoverAlpha"] = 1,
["showPagingArrows"] = false,
["orientation"] = "horizontal",
["mouseoverSpeed"] = 0.15,
["hideMacroText"] = false,
["visHideNoEnemy"] = false,
},
["Bar2"] = {
["visOnlyInstances"] = false,
["buttonPadding"] = 0,
["combatShowEnabled"] = false,
["targetWidth"] = 0,
["bgEnabled"] = true,
["buttonHeight"] = 40,
["numRows"] = 1,
["hideMacroText"] = false,
["countFontColor"] = {
["b"] = 1,
["g"] = 1,
["r"] = 1,
},
["borderThickness"] = "thin",
["enabled"] = true,
["borderColor"] = {
["a"] = 1,
["r"] = 0.04495855084757916,
["g"] = 0.6449502660937397,
["b"] = 0.6796151221762596,
},
["keybindOffsetX"] = 0,
["buttonShape"] = "none",
["bgPadX"] = 0,
["disableTooltips"] = false,
["alwaysHidden"] = false,
["outOfRangeColoring"] = true,
["clickThrough"] = false,
["targetHeight"] = 0,
["barVisibility"] = "always",
["visHideHousing"] = false,
["keybindFontColor"] = {
["b"] = 1,
["g"] = 1,
["r"] = 1,
},
["overrideNumIcons"] = 12,
["cooldownTextXOffset"] = 0,
["borderClassColor"] = false,
["cooldownTextYOffset"] = 0,
["housingHideEnabled"] = false,
["cooldownTextColor"] = {
["b"] = 1,
["g"] = 1,
["r"] = 1,
},
["bgPadY"] = 0,
["keybindFontSize"] = 12,
["hideKeybind"] = false,
["countFontSize"] = 12,
["visHideMounted"] = false,
["macroOffsetX"] = 0,
["macroOffsetY"] = 0,
["visHideNoTarget"] = false,
["countOffsetX"] = 0,
["macroFontSize"] = 12,
["borderEnabled"] = true,
["bgColor"] = {
["a"] = 0.5,
["b"] = 0,
["g"] = 0,
["r"] = 0,
},
["mouseoverAlpha"] = 1,
["shapeBorderColor"] = {
["a"] = 1,
["r"] = 0.04495855084757916,
["g"] = 0.6449502660937397,
["b"] = 0.6796151221762596,
},
["growDirection"] = "up",
["combatHideEnabled"] = false,
["shapeBorderEnabled"] = true,
["outOfRangeColor"] = {
["b"] = 0.1,
["g"] = 0.1,
["r"] = 0.8,
},
["numIcons"] = 12,
["borderSize"] = 1,
["mouseoverEnabled"] = false,
["pagingArrowsRight"] = false,
["macroFontColor"] = {
["b"] = 1,
["g"] = 1,
["r"] = 1,
},
["keybindOffsetY"] = 0,
["shapeBorderSize"] = 7,
["alwaysShowButtons"] = true,
["buttonWidth"] = 40,
["overrideNumRows"] = 3,
["cooldownFontSize"] = 12,
["iconZoom"] = 5.5,
["showPagingArrows"] = false,
["orientation"] = "horizontal",
["mouseoverSpeed"] = 0.15,
["visHideNoEnemy"] = false,
["countOffsetY"] = 0,
},
["Bar5"] = {
["visOnlyInstances"] = false,
["borderThickness"] = "thin",
["combatShowEnabled"] = false,
["targetWidth"] = 0,
["bgEnabled"] = true,
["numRows"] = 1,
["buttonPadding"] = 0,
["countFontColor"] = {
["b"] = 1,
["g"] = 1,
["r"] = 1,
},
["buttonHeight"] = 40,
["borderColor"] = {
["a"] = 1,
["b"] = 0,
["g"] = 0,
["r"] = 0,
},
["hideMacroText"] = false,
["keybindOffsetX"] = 0,
["alwaysHidden"] = false,
["bgPadX"] = 0,
["disableTooltips"] = false,
["enabled"] = true,
["outOfRangeColoring"] = true,
["visHideHousing"] = false,
["showPagingArrows"] = false,
["targetHeight"] = 0,
["keybindFontColor"] = {
["b"] = 1,
["g"] = 1,
["r"] = 1,
},
["cooldownFontSize"] = 12,
["buttonShape"] = "none",
["cooldownTextXOffset"] = 0,
["buttonWidth"] = 40,
["cooldownTextColor"] = {
["b"] = 1,
["g"] = 1,
["r"] = 1,
},
["housingHideEnabled"] = false,
["overrideNumRows"] = 3,
["borderSize"] = 1,
["keybindFontSize"] = 12,
["hideKeybind"] = false,
["countFontSize"] = 12,
["visHideMounted"] = false,
["bgPadY"] = 0,
["macroOffsetX"] = 0,
["visHideNoTarget"] = false,
["macroOffsetY"] = 0,
["macroFontSize"] = 12,
["countOffsetX"] = 0,
["bgColor"] = {
["a"] = 0.5,
["b"] = 0,
["g"] = 0,
["r"] = 0,
},
["mouseoverAlpha"] = 1,
["shapeBorderColor"] = {
["a"] = 1,
["b"] = 0,
["g"] = 0,
["r"] = 0,
},
["growDirection"] = "up",
["combatHideEnabled"] = false,
["shapeBorderEnabled"] = true,
["outOfRangeColor"] = {
["b"] = 0.1,
["g"] = 0.1,
["r"] = 0.8,
},
["borderEnabled"] = true,
["numIcons"] = 12,
["mouseoverEnabled"] = false,
["pagingArrowsRight"] = false,
["macroFontColor"] = {
["b"] = 1,
["g"] = 1,
["r"] = 1,
},
["keybindOffsetY"] = 0,
["shapeBorderSize"] = 7,
["cooldownTextYOffset"] = 0,
["overrideNumIcons"] = 12,
["borderClassColor"] = true,
["alwaysShowButtons"] = true,
["barVisibility"] = "always",
["clickThrough"] = false,
["orientation"] = "horizontal",
["mouseoverSpeed"] = 0.15,
["visHideNoEnemy"] = false,
["countOffsetY"] = 0,
},
["MainBar"] = {
["countOffsetY"] = 0,
["borderThickness"] = "thin",
["combatShowEnabled"] = false,
["targetWidth"] = 0,
["buttonHeight"] = 40,
["buttonPadding"] = 0,
["numRows"] = 1,
["visOnlyInstances"] = false,
["countFontColor"] = {
["b"] = 1,
["g"] = 1,
["r"] = 1,
},
["bgEnabled"] = true,
["hideMacroText"] = false,
["borderColor"] = {
["a"] = 1,
["b"] = 0,
["g"] = 0,
["r"] = 0,
},
["keybindOffsetX"] = 0,
["enabled"] = true,
["bgPadX"] = 0,
["disableTooltips"] = false,
["alwaysHidden"] = false,
["outOfRangeColoring"] = true,
["buttonShape"] = "none",
["cooldownFontSize"] = 12,
["targetHeight"] = 0,
["overrideNumRows"] = 3,
["keybindFontColor"] = {
["b"] = 1,
["g"] = 1,
["r"] = 1,
},
["buttonWidth"] = 40,
["cooldownTextXOffset"] = 0,
["borderClassColor"] = true,
["mouseoverEnabled"] = false,
["housingHideEnabled"] = false,
["cooldownTextColor"] = {
["b"] = 1,
["g"] = 1,
["r"] = 1,
},
["bgPadY"] = 0,
["keybindFontSize"] = 12,
["hideKeybind"] = false,
["countFontSize"] = 12,
["visHideMounted"] = false,
["macroOffsetX"] = 0,
["macroOffsetY"] = 0,
["visHideNoTarget"] = false,
["countOffsetX"] = 0,
["macroFontSize"] = 12,
["borderEnabled"] = true,
["bgColor"] = {
["a"] = 0.5,
["b"] = 0,
["g"] = 0,
["r"] = 0,
},
["mouseoverAlpha"] = 1,
["shapeBorderColor"] = {
["a"] = 1,
["b"] = 0,
["g"] = 0,
["r"] = 0,
},
["growDirection"] = "up",
["combatHideEnabled"] = false,
["shapeBorderEnabled"] = true,
["outOfRangeColor"] = {
["b"] = 0.1,
["g"] = 0.1,
["r"] = 0.8,
},
["numIcons"] = 12,
["borderSize"] = 1,
["cooldownTextYOffset"] = 0,
["pagingArrowsRight"] = false,
["macroFontColor"] = {
["b"] = 1,
["g"] = 1,
["r"] = 1,
},
["keybindOffsetY"] = 0,
["shapeBorderSize"] = 7,
["alwaysShowButtons"] = true,
["overrideNumIcons"] = 12,
["clickThrough"] = false,
["barVisibility"] = "always",
["iconZoom"] = 5.5,
["visHideHousing"] = false,
["orientation"] = "horizontal",
["mouseoverSpeed"] = 0.15,
["showPagingArrows"] = false,
["visHideNoEnemy"] = false,
},
["RepBar"] = {
["alwaysHidden"] = false,
["mouseoverEnabled"] = false,
["combatShowEnabled"] = false,
["combatHideEnabled"] = false,
["width"] = 400,
["mouseoverAlpha"] = 1,
["barVisibility"] = "always",
["housingHideEnabled"] = false,
["height"] = 18,
["mouseoverSpeed"] = 0.15,
["orientation"] = "HORIZONTAL",
["clickThrough"] = true,
},
["Bar7"] = {
["countOffsetY"] = 0,
["borderThickness"] = "thin",
["combatShowEnabled"] = false,
["targetWidth"] = 0,
["buttonHeight"] = 40,
["numRows"] = 1,
["buttonPadding"] = 0,
["countFontColor"] = {
["b"] = 1,
["g"] = 1,
["r"] = 1,
},
["visOnlyInstances"] = false,
["bgEnabled"] = true,
["borderColor"] = {
["a"] = 1,
["b"] = 0,
["g"] = 0,
["r"] = 0,
},
["keybindOffsetX"] = 0,
["alwaysHidden"] = true,
["bgPadX"] = 0,
["disableTooltips"] = false,
["enabled"] = true,
["outOfRangeColoring"] = true,
["barVisibility"] = "never",
["buttonShape"] = "none",
["targetHeight"] = 0,
["keybindFontColor"] = {
["b"] = 1,
["g"] = 1,
["r"] = 1,
},
["cooldownFontSize"] = 12,
["visHideHousing"] = false,
["cooldownTextXOffset"] = 0,
["overrideNumIcons"] = 12,
["overrideNumRows"] = 3,
["housingHideEnabled"] = false,
["cooldownTextColor"] = {
["b"] = 1,
["g"] = 1,
["r"] = 1,
},
["borderEnabled"] = true,
["keybindFontSize"] = 12,
["hideKeybind"] = false,
["countFontSize"] = 12,
["visHideMounted"] = false,
["bgPadY"] = 0,
["macroOffsetX"] = 0,
["visHideNoTarget"] = false,
["macroOffsetY"] = 0,
["macroFontSize"] = 12,
["cooldownTextYOffset"] = 0,
["bgColor"] = {
["a"] = 0.5,
["b"] = 0,
["g"] = 0,
["r"] = 0,
},
["borderSize"] = 1,
["shapeBorderColor"] = {
["a"] = 1,
["b"] = 0,
["g"] = 0,
["r"] = 0,
},
["growDirection"] = "up",
["clickThrough"] = false,
["shapeBorderEnabled"] = true,
["combatHideEnabled"] = false,
["outOfRangeColor"] = {
["b"] = 0.1,
["g"] = 0.1,
["r"] = 0.8,
},
["numIcons"] = 12,
["countOffsetX"] = 0,
["pagingArrowsRight"] = false,
["macroFontColor"] = {
["b"] = 1,
["g"] = 1,
["r"] = 1,
},
["keybindOffsetY"] = 0,
["shapeBorderSize"] = 7,
["mouseoverEnabled"] = false,
["buttonWidth"] = 40,
["borderClassColor"] = true,
["alwaysShowButtons"] = true,
["mouseoverAlpha"] = 1,
["showPagingArrows"] = false,
["orientation"] = "horizontal",
["mouseoverSpeed"] = 0.15,
["hideMacroText"] = false,
["visHideNoEnemy"] = false,
},
["BagBar"] = {
["alwaysHidden"] = false,
["mouseoverEnabled"] = false,
["combatShowEnabled"] = false,
["combatHideEnabled"] = false,
["mouseoverAlpha"] = 1,
["clickThrough"] = false,
["mouseoverSpeed"] = 0.15,
["barVisibility"] = "always",
["housingHideEnabled"] = false,
},
["MicroBar"] = {
["alwaysHidden"] = false,
["mouseoverEnabled"] = false,
["combatShowEnabled"] = false,
["combatHideEnabled"] = false,
["mouseoverAlpha"] = 1,
["clickThrough"] = false,
["mouseoverSpeed"] = 0.15,
["barVisibility"] = "always",
["housingHideEnabled"] = false,
},
["StanceBar"] = {
["countOffsetY"] = 0,
["borderThickness"] = "thin",
["combatShowEnabled"] = false,
["targetWidth"] = 0,
["bgEnabled"] = true,
["numRows"] = 1,
["buttonPadding"] = 0,
["countFontColor"] = {
["b"] = 1,
["g"] = 1,
["r"] = 1,
},
["visOnlyInstances"] = false,
["buttonHeight"] = 40,
["borderColor"] = {
["a"] = 1,
["b"] = 0,
["g"] = 0,
["r"] = 0,
},
["keybindOffsetX"] = 0,
["alwaysHidden"] = true,
["bgPadX"] = 0,
["disableTooltips"] = false,
["enabled"] = true,
["outOfRangeColoring"] = true,
["barVisibility"] = "never",
["buttonShape"] = "none",
["targetHeight"] = 0,
["keybindFontColor"] = {
["b"] = 1,
["g"] = 1,
["r"] = 1,
},
["cooldownFontSize"] = 12,
["visHideHousing"] = false,
["cooldownTextXOffset"] = 0,
["buttonWidth"] = 40,
["overrideNumRows"] = 3,
["housingHideEnabled"] = false,
["cooldownTextColor"] = {
["b"] = 1,
["g"] = 1,
["r"] = 1,
},
["borderEnabled"] = true,
["keybindFontSize"] = 12,
["hideKeybind"] = false,
["countFontSize"] = 12,
["visHideMounted"] = false,
["bgPadY"] = 0,
["macroOffsetX"] = 0,
["visHideNoTarget"] = false,
["macroOffsetY"] = 0,
["macroFontSize"] = 12,
["cooldownTextYOffset"] = 0,
["bgColor"] = {
["a"] = 0.5,
["b"] = 0,
["g"] = 0,
["r"] = 0,
},
["borderSize"] = 1,
["shapeBorderColor"] = {
["a"] = 1,
["b"] = 0,
["g"] = 0,
["r"] = 0,
},
["growDirection"] = "up",
["clickThrough"] = false,
["shapeBorderEnabled"] = true,
["combatHideEnabled"] = false,
["outOfRangeColor"] = {
["b"] = 0.1,
["g"] = 0.1,
["r"] = 0.8,
},
["numIcons"] = 12,
["countOffsetX"] = 0,
["pagingArrowsRight"] = false,
["macroFontColor"] = {
["b"] = 1,
["g"] = 1,
["r"] = 1,
},
["keybindOffsetY"] = 0,
["shapeBorderSize"] = 7,
["mouseoverEnabled"] = false,
["overrideNumIcons"] = 12,
["borderClassColor"] = true,
["alwaysShowButtons"] = true,
["mouseoverAlpha"] = 1,
["showPagingArrows"] = false,
["orientation"] = "horizontal",
["mouseoverSpeed"] = 0.15,
["hideMacroText"] = false,
["visHideNoEnemy"] = false,
},
["QueueStatus"] = {
["alwaysHidden"] = false,
["mouseoverEnabled"] = false,
["combatShowEnabled"] = false,
["combatHideEnabled"] = false,
["mouseoverAlpha"] = 1,
["clickThrough"] = false,
["mouseoverSpeed"] = 0.15,
["barVisibility"] = "always",
["housingHideEnabled"] = false,
},
["Bar4"] = {
["visOnlyInstances"] = false,
["buttonPadding"] = 0,
["combatShowEnabled"] = false,
["targetWidth"] = 0,
["buttonHeight"] = 44,
["numRows"] = 1,
["bgEnabled"] = true,
["countFontColor"] = {
["b"] = 1,
["g"] = 1,
["r"] = 1,
},
["hideMacroText"] = false,
["borderThickness"] = "thin",
["borderColor"] = {
["a"] = 1,
["b"] = 0,
["g"] = 0,
["r"] = 0,
},
["keybindOffsetX"] = 0,
["enabled"] = true,
["bgPadX"] = 0,
["disableTooltips"] = false,
["alwaysHidden"] = false,
["outOfRangeColoring"] = true,
["targetHeight"] = 0,
["buttonShape"] = "none",
["barVisibility"] = "always",
["keybindFontColor"] = {
["b"] = 1,
["g"] = 1,
["r"] = 1,
},
["cooldownFontSize"] = 12,
["visHideHousing"] = false,
["cooldownTextXOffset"] = 0,
["overrideNumIcons"] = 1,
["countOffsetX"] = 0,
["housingHideEnabled"] = false,
["cooldownTextColor"] = {
["b"] = 1,
["g"] = 1,
["r"] = 1,
},
["borderEnabled"] = true,
["keybindFontSize"] = 12,
["hideKeybind"] = false,
["countFontSize"] = 12,
["visHideMounted"] = false,
["bgPadY"] = 0,
["macroOffsetX"] = 0,
["visHideNoTarget"] = false,
["macroOffsetY"] = 0,
["macroFontSize"] = 12,
["cooldownTextYOffset"] = 0,
["bgColor"] = {
["a"] = 0.5,
["b"] = 0,
["g"] = 0,
["r"] = 0,
},
["borderSize"] = 1,
["shapeBorderColor"] = {
["a"] = 1,
["b"] = 0,
["g"] = 0,
["r"] = 0,
},
["growDirection"] = "up",
["clickThrough"] = false,
["shapeBorderEnabled"] = true,
["combatHideEnabled"] = false,
["outOfRangeColor"] = {
["b"] = 0.1,
["g"] = 0.1,
["r"] = 0.8,
},
["numIcons"] = 12,
["mouseoverEnabled"] = false,
["pagingArrowsRight"] = false,
["macroFontColor"] = {
["b"] = 1,
["g"] = 1,
["r"] = 1,
},
["keybindOffsetY"] = 0,
["shapeBorderSize"] = 7,
["borderClassColor"] = false,
["buttonWidth"] = 44,
["alwaysShowButtons"] = true,
["mouseoverAlpha"] = 1,
["overrideNumRows"] = 3,
["showPagingArrows"] = false,
["orientation"] = "vertical",
["mouseoverSpeed"] = 0.15,
["visHideNoEnemy"] = false,
["countOffsetY"] = 0,
},
},
["cooldownEdgeSize"] = 2.1,
["procGlowEnabled"] = false,
},
["EllesmereUIMythicPlus"] = {
["enabled"] = true,
["showSplits"] = true,
["scale"] = 1,
["showBossList"] = true,
["bestTimes"] = {
},
["position"] = {
["y"] = 225.4869537353516,
["x"] = 0,
["point"] = "RIGHT",
["relativePoint"] = "RIGHT",
},
["locked"] = false,
["showDeathCounter"] = true,
["showAffixes"] = true,
},
["EllesmereUIBasics"] = {
["friends"] = {
["visHideHousing"] = false,
["visHideNoEnemy"] = false,
["showClassIcons"] = true,
["tileR"] = 0,
["groupsEnabled"] = true,
["borderA"] = 1,
["iconStyle"] = "modern",
["enabled"] = true,
["tileAlpha"] = 0.35,
["showRegionIcons"] = true,
["borderG"] = 0,
["visibility"] = "always",
["accentColors"] = true,
["bgR"] = 0.05,
["visHideMounted"] = false,
["borderB"] = 0,
["bgAlpha"] = 1,
["scale"] = 1,
["borderSize"] = 1,
["borderR"] = 0,
["bgB"] = 0.055,
["showBorder"] = true,
["tileB"] = 0,
["showOffline"] = true,
["visHideNoTarget"] = false,
["factionBanners"] = false,
["nameColorB"] = 0.565,
["autoAcceptFriendInvites"] = false,
["nameColorG"] = 0.82,
["showUngrouped"] = true,
["classColorNames"] = true,
["visOnlyInstances"] = false,
["bgG"] = 0.05,
["useAccentTab"] = true,
["nameColorR"] = 0.863,
["useClassColor"] = false,
["tileG"] = 0,
},
["minimap"] = {
["visOnlyInstances"] = false,
["customBtnSizeEnabled"] = false,
["visHideNoEnemy"] = false,
["btnPositions"] = {
},
["ungroupedButtons"] = {
},
["hideCraftingOrder"] = false,
["borderA"] = 1,
["btnBackgrounds"] = true,
["clockInside"] = true,
["showClock"] = true,
["_capturedOnce"] = true,
["locationOffsetY"] = 0,
["mapSize"] = 200,
["hideAddonCompartment"] = false,
["hideAddonButtons"] = false,
["clockFormat"] = "12h",
["interactableBtnSize"] = 21,
["borderG"] = 0,
["savedZoom"] = 0,
["shape"] = "square",
["locationScale"] = 1.15,
["visHideMounted"] = false,
["borderB"] = 0,
["scrollZoom"] = true,
["visHideNoTarget"] = false,
["clockOffsetX"] = 0,
["hideZoomButtons"] = true,
["borderSize"] = 1,
["borderR"] = 0,
["position"] = {
["y"] = 457.025641025641,
["relPoint"] = "CENTER",
["point"] = "CENTER",
["x"] = 956.7179487179487,
},
["coordPrecision"] = 0,
["enabled"] = true,
["visHideHousing"] = false,
["visibility"] = "always",
["lock"] = false,
["hideGameTime"] = false,
["hideMail"] = false,
["clockOffsetY"] = 0,
["hideTrackingButton"] = true,
["locationOffsetX"] = 0,
["freeMoveBtns"] = false,
["customBtnSize"] = 24,
["clockScale"] = 1.15,
["addonBtnSize"] = 24,
["showCoords"] = false,
["zoneInside"] = false,
["hideRaidDifficulty"] = false,
["useClassColor"] = false,
["hideZoneText"] = false,
},
["questTracker"] = {
["visOnlyInstances"] = false,
["visHideNoEnemy"] = false,
["autoAccept"] = false,
["showZoneQuests"] = true,
["secColorUseAccent"] = true,
["autoTurnInShiftSkip"] = true,
["enabled"] = false,
["showTopLine"] = true,
["worldCollapsed"] = false,
["titleFontSize"] = 14,
["completedFontSize"] = 11,
["completedColor"] = {
["b"] = 0.35,
["g"] = 1,
["r"] = 0.25,
},
["secColor"] = {
["r"] = 0.5188487377577926,
["g"] = 0.2191020422339023,
["b"] = 1,
},
["height"] = 500,
["questsCollapsed"] = true,
["visibility"] = "out_of_combat",
["pos"] = {
["y"] = -18.87179487179487,
["relPoint"] = "CENTER",
["point"] = "CENTER",
["x"] = 905.025641025641,
},
["bgR"] = 0,
["visHideMounted"] = false,
["bgAlpha"] = 0.35,
["visHideNoTarget"] = false,
["showWorldQuests"] = true,
["showQuestItems"] = true,
["focusedFontSize"] = 12,
["bgB"] = 0,
["objColor"] = {
["b"] = 0.72,
["g"] = 0.72,
["r"] = 0.72,
},
["hideBlizzardTracker"] = true,
["zoneCollapsed"] = true,
["questItemSize"] = 22,
["objFontSize"] = 13,
["_capturedOnce"] = true,
["recipesCollapsed"] = false,
["autoTurnIn"] = false,
["width"] = 300,
["showPreyQuests"] = true,
["preyCollapsed"] = false,
["alignment"] = "top",
["bgG"] = 0,
["visHideHousing"] = false,
["delveCollapsed"] = false,
["titleColor"] = {
["b"] = 0.47,
["g"] = 0.91,
["r"] = 1,
},
["secFontSize"] = 16,
},
["cursor"] = {
["enabled"] = true,
["visHideMounted"] = false,
["visHideNoEnemy"] = false,
["scale"] = 1.4,
["hex"] = "0CD29D",
["useClassColor"] = false,
["visHideNoTarget"] = false,
["trail"] = true,
["castCircle"] = {
["instanceOnly"] = false,
["radius"] = 30,
["scale"] = 100,
["attached"] = true,
["alpha"] = 80,
["sparkEnabled"] = true,
["ringTex"] = "normal",
["enabled"] = true,
["useClassColor"] = false,
["hex"] = "3FA7FF",
},
["visHideHousing"] = false,
["visOnlyInstances"] = false,
["instanceOnly"] = false,
["gcd"] = {
["instanceOnly"] = false,
["radius"] = 21,
["scale"] = 100,
["attached"] = true,
["alpha"] = 80,
["ringTex"] = "light",
["enabled"] = false,
["useClassColor"] = false,
["hex"] = "FFFFFF",
},
["visibility"] = "always",
["texture"] = "ring_thick",
},
["chat"] = {
["visOnlyInstances"] = false,
["classColorNames"] = true,
["borderB"] = 0.05,
["bgAlpha"] = 0.6,
["messageFadeTime"] = 120,
["copyButton"] = false,
["borderA"] = 1,
["borderR"] = 0.05,
["fontOutline"] = "",
["hideTabFlash"] = false,
["visibility"] = "always",
["copyLines"] = 200,
["enabled"] = false,
["hideButtons"] = false,
["messageSpacing"] = 0,
["messageFadeEnabled"] = true,
["fontSize"] = 14,
["visHideMounted"] = false,
["timestamps"] = "none",
["showSearchButton"] = true,
["clickableURLs"] = true,
["visHideNoEnemy"] = false,
["shortenChannels"] = "off",
["borderG"] = 0.05,
["fontShadow"] = true,
["visHideHousing"] = false,
["useClassColor"] = false,
["visHideNoTarget"] = false,
},
},
["EllesmereUINameplates"] = {
["friendlyShowDefaultNames"] = false,
["textSlotRight"] = "healthPercent",
["topSlotSize"] = 26,
["focusColorEnabled"] = true,
["dispelGlowUseTypeColor"] = false,
["showFriendlyNPCs"] = false,
["castBarUninterruptible"] = {
["b"] = 0.45,
["g"] = 0.45,
["r"] = 0.45,
},
["leftSlotXOffset"] = 0,
["toprightSlotXOffset"] = 0,
["castBarHeight"] = 17,
["textSlotTop"] = "none",
["auraDurationTextSize"] = 11,
["importantCastGlowSpeed"] = 4,
["topleftSlotGrowth"] = "left",
["tapped"] = {
["b"] = 0.5,
["g"] = 0.5,
["r"] = 0.5,
},
["friendlyNameOnlyYOffset"] = -20,
["targetScale"] = 100,
["healthBarTexture"] = "melli",
["raidMarkerSize"] = 24,
["nameYOffset"] = 0,
["textSlotRightColor"] = {
["b"] = 0.03615391657898393,
["g"] = 1,
["r"] = 0,
},
["auraDurationTextColor"] = {
["b"] = 1,
["g"] = 1,
["r"] = 1,
},
["textSlotTopXOffset"] = 0,
["classPowerCustomColor"] = {
["b"] = 0.3,
["g"] = 0.84,
["r"] = 1,
},
["offTankAggro"] = {
["b"] = 0.812,
["g"] = 0.761,
["r"] = 0.188,
},
["topSlotYOffset"] = 0,
["pandemicGlowSpeed"] = 4,
["buffIconSize"] = 24,
["caster"] = {
["b"] = 0.9478205021363408,
["g"] = 0.2180848909722149,
["r"] = 0.2037807915162192,
},
["offTankAggroEnabled"] = true,
["questMobColorEnabled"] = true,
["importantCastGlowThickness"] = 3,
["topleftSlotXOffset"] = 0,
["importantCastGlowLines"] = 10,
["focusOverlayAlpha"] = 0.5,
["hitboxScaleX"] = 100,
["castTimerSize"] = 10,
["classPowerEmptyColor"] = {
["a"] = 1,
["b"] = 0.2,
["g"] = 0.2,
["r"] = 0.2,
},
["miniboss"] = {
["b"] = 0.984,
["g"] = 0.243,
["r"] = 0.518,
},
["buffTimerPosition"] = "topleft",
["auraStackTextColor"] = {
["b"] = 1,
["g"] = 1,
["r"] = 1,
},
["focusCastHeight"] = 100,
["bottomSlotXOffset"] = 0,
["raidMarkerPos"] = "topright",
["enemyInCombat"] = {
["b"] = 0.137,
["g"] = 0.137,
["r"] = 0.8,
},
["dispelGlowStyle"] = 2,
["auraStackTextSize"] = 12,
["topSlotXOffset"] = 0,
["simpleBorderSize"] = 6,
["dispelGlowColor"] = {
["b"] = 1,
["g"] = 1,
["r"] = 1,
},
["tankHasAggro"] = {
["b"] = 0.62,
["g"] = 0.82,
["r"] = 0.05,
},
["ccIconSize"] = 24,
["classicTankAggro"] = true,
["topleftSlotSize"] = 24,
["textSlotLeft"] = "healthNumber",
["castNameSize"] = 10,
["bottomSlotSize"] = 26,
["castIconScale"] = 1,
["textSlotCenterColor"] = {
["b"] = 1,
["g"] = 1,
["r"] = 1,
},
["buffTextColor"] = {
["b"] = 1,
["g"] = 1,
["r"] = 1,
},
["dispelGlow"] = false,
["classificationSlot"] = "none",
["friendlyPlateYOffset"] = 0,
["castNameColor"] = {
["b"] = 1,
["g"] = 1,
["r"] = 1,
},
["classPowerXOffset"] = 0,
["kickTickEnabled"] = true,
["targetArrowScale"] = 1.8,
["castBar"] = {
["b"] = 0.7694318438898894,
["g"] = 0.04646508300669783,
["r"] = 0.9929484801884899,
},
["enemyNameTextSize"] = 11,
["borderColor"] = {
["b"] = 0,
["g"] = 0,
["r"] = 0,
},
["classPowerBgColor"] = {
["a"] = 1,
["b"] = 0.082,
["g"] = 0.082,
["r"] = 0.082,
},
["friendlyBarColor"] = {
["b"] = 0.408,
["g"] = 0.8,
["r"] = 0.314,
},
["tankLosingAggro"] = {
["b"] = 0.19,
["g"] = 0.72,
["r"] = 0.81,
},
["buffSlot"] = "left",
["sideAuraXOffset"] = 2,
["classPowerClassColors"] = true,
["borderStyle"] = "simple",
["tankHasAggroEnabled"] = true,
["pandemicGlow"] = false,
["buffTextSize"] = 12,
["rightSlotXOffset"] = 0,
["neutral"] = {
["b"] = 0.19,
["g"] = 0.72,
["r"] = 0.81,
},
["kickTickColor"] = {
["b"] = 1,
["g"] = 1,
["r"] = 1,
},
["showFriendlyPlayers"] = true,
["dpsNearAggro"] = {
["b"] = 0.19,
["g"] = 0.72,
["r"] = 0.81,
},
["castTargetClassColor"] = true,
["textSlotLeftYOffset"] = 0,
["focus"] = {
["b"] = 0,
["g"] = 0,
["r"] = 0,
},
["toprightSlotGrowth"] = "right",
["textSlotCenterSize"] = 10,
["textSlotTopYOffset"] = 0,
["ccTimerPosition"] = "topleft",
["pandemicGlowColor"] = {
["b"] = 0,
["g"] = 1,
["r"] = 1,
},
["textSlotLeftSize"] = 10,
["textSlotCenterYOffset"] = 0,
["targetGlowStyle"] = "vibrant",
["textSlotRightXOffset"] = 0,
["textSlotRightSize"] = 10,
["questMobColor"] = {
["b"] = 0.475,
["g"] = 0.855,
["r"] = 0.157,
},
["nameplateYOffset"] = 0,
["textSlotRightYOffset"] = 0,
["healthBarWidth"] = 50,
["textSlotTopColor"] = {
["b"] = 1,
["g"] = 1,
["r"] = 1,
},
["showAllDebuffs"] = true,
["interruptReady"] = {
["b"] = 0.05910267591005891,
["g"] = 0.2551229517621299,
["r"] = 1,
},
["nameplateOverlapV"] = 1.05,
["classColorFriendly"] = true,
["rareEliteIconSize"] = 20,
["showCastIcon"] = true,
["castTargetSize"] = 10,
["leftSlotYOffset"] = 0,
["classPowerYOffset"] = 1,
["textSlotLeftXOffset"] = 0,
["debuffIconSize"] = 26,
["bottomSlotYOffset"] = 0,
["showTargetArrows"] = true,
["topleftSlotYOffset"] = 0,
["castTimerColor"] = {
["b"] = 1,
["g"] = 1,
["r"] = 1,
},
["hitboxScaleY"] = 100,
["importantCastGlowStyle"] = 1,
["textSlotTopSize"] = 10,
["textSlotLeftColor"] = {
["b"] = 0,
["g"] = 0.9776959734132578,
["r"] = 1,
},
["showEnemyPets"] = false,
["friendlyNameOnly"] = true,
["hashLineColor"] = {
["b"] = 1,
["g"] = 1,
["r"] = 1,
},
["focusOverlayColor"] = {
["b"] = 0.9683333869046254,
["g"] = 0.005586841568303802,
["r"] = 0.9350088088420117,
},
["debuffTimerColor"] = {
["b"] = 1,
["g"] = 1,
["r"] = 1,
},
["importantCastGlowColor"] = {
["b"] = 0.2,
["g"] = 0.2,
["r"] = 1,
},
["textSlotCenter"] = "enemyName",
["textSlotCenterXOffset"] = 0,
["ccTextColor"] = {
["b"] = 1,
["g"] = 1,
["r"] = 1,
},
["healthBarHeight"] = 24,
["rightSlotSize"] = 24,
["friendlyHealthBarHeight"] = 17,
["castTargetColor"] = {
["b"] = 1,
["g"] = 1,
["r"] = 1,
},
["tankNoAggro"] = {
["b"] = 0.17,
["g"] = 0.22,
["r"] = 1,
},
["ccTextSize"] = 12,
["hashLinePercent"] = 30,
["castScale"] = 100,
["importantCastGlow"] = true,
["showCastTimer"] = true,
["classPowerPos"] = "bottom",
["dpsHasAggro"] = {
["b"] = 0,
["g"] = 0.5,
["r"] = 1,
},
["hashLineEnabled"] = false,
["pandemicGlowLines"] = 8,
["hostile"] = {
["b"] = 0.09,
["g"] = 0.11,
["r"] = 0.39,
},
["focusOverlayTexture"] = "striped-v2",
["friendlyHealthBarWidth"] = 150,
["auraSpacing"] = 2,
["rightSlotYOffset"] = 0,
["pandemicGlowThickness"] = 2,
["castOverlayEnabled"] = false,
["debuffSlot"] = "top",
["stackingEnabled"] = true,
["toprightSlotSize"] = 24,
["leftSlotSize"] = 24,
["debuffTimerPosition"] = "topleft",
["ccSlot"] = "right",
["toprightSlotYOffset"] = 0,
["debuffYOffset"] = 2,
["auraTextPosition"] = "topleft",
["pandemicGlowStyle"] = 1,
["classPowerGap"] = 2,
["classPowerScale"] = 1,
["stackSpacingScale"] = 160,
["showClassPower"] = false,
["font"] = "Interface\\AddOns\\EllesmereUI\\media\\fonts\\Expressway.TTF",
},
["EllesmereUIAuraBuffReminders"] = {
["consumables"] = {
["enabled"] = {
["es"] = true,
["augment_rune"] = true,
["tstrike"] = true,
["flask"] = true,
["ls"] = true,
["wound"] = true,
["inky_black"] = true,
["ws"] = true,
["food"] = true,
["numbing"] = true,
["earthliving"] = true,
["instant"] = true,
["deadly"] = true,
["windfury"] = true,
["atrophic"] = true,
["amplifying"] = true,
["rite_adj"] = true,
["flametongue"] = true,
["rite_sanc"] = true,
["weapon_enchant"] = true,
["crippling"] = true,
},
["inkyBlackZones"] = "",
["showSpecialsNonInstanced"] = true,
["preferredWeaponEnchant"] = "last_used",
["scale"] = 1,
["preferredFood"] = "last_used",
["runeDisplayMode"] = "mythic",
["preferredFlask"] = "last_used",
},
["talentReminders"] = {
},
["talentReminderYOffset"] = -50,
["display"] = {
["textFont"] = "Expressway",
["scale"] = 1,
["glowType"] = 0,
["cursorAttach"] = false,
["opacity"] = 1,
["frameStrata"] = "MEDIUM",
["yOffset"] = 200,
["glowColor"] = {
["b"] = 0.376,
["g"] = 0.776,
["r"] = 1,
},
["iconSpacing"] = 14,
["showText"] = true,
["textYOffset"] = -5,
["xOffset"] = 0,
["textXOffset"] = 0,
["textSize"] = 12,
["textColor"] = {
["b"] = 1,
["g"] = 1,
["r"] = 1,
},
},
["unlockPos"] = {
["y"] = 22.15384615384615,
["relPoint"] = "CENTER",
["point"] = "CENTER",
["x"] = 415.1794871794872,
},
["raidBuffs"] = {
["enabled"] = {
["ai"] = true,
["sky"] = true,
["bshout"] = true,
["hmark"] = true,
["motw"] = true,
["bronze"] = true,
["fort"] = true,
},
["showNonInstanced"] = false,
["scale"] = 1,
["showOthersMissing"] = true,
},
["auras"] = {
["enabled"] = {
["som"] = true,
["devo_aura"] = true,
["bestow_weyrnstone"] = true,
["bof"] = true,
["bol"] = true,
["shadowform"] = true,
["timelessness"] = true,
["berserk_stance"] = true,
["blistering_scales"] = true,
["symbiotic"] = true,
["def_stance"] = true,
},
["showNonInstanced"] = true,
["scale"] = 1,
},
},
["EllesmereUIUnitFrames"] = {
["castbarOpacity"] = 1,
["enabledFrames"] = {
["boss"] = true,
["player"] = true,
["focus"] = true,
["target"] = true,
["focustarget"] = true,
["targettarget"] = true,
["pet"] = true,
},
["positions"] = {
["focusCastbar"] = {
["point"] = "CENTER",
["relPoint"] = "CENTER",
},
["focustarget"] = {
["y"] = -294.5641133686499,
["x"] = 413.5384767069625,
["point"] = "CENTER",
["relPoint"] = "CENTER",
},
["targettarget"] = {
["y"] = -160.8205187193743,
["x"] = 383.1795012344276,
["point"] = "CENTER",
["relPoint"] = "CENTER",
},
["player"] = {
["y"] = -221.5384696644442,
["x"] = -315.8974474844852,
["point"] = "CENTER",
["relPoint"] = "CENTER",
},
["pet"] = {
["y"] = -260.1025736430697,
["x"] = -316.7179603350943,
["point"] = "CENTER",
["relPoint"] = "CENTER",
},
["focus"] = {
["y"] = -342.1538587039749,
["x"] = 413.5384767069625,
["point"] = "CENTER",
["relPoint"] = "CENTER",
},
["target"] = {
["y"] = -221.5384696644442,
["x"] = 315.8974474844852,
["point"] = "CENTER",
["relPoint"] = "CENTER",
},
["classPower"] = {
["y"] = -220,
["relPoint"] = "CENTER",
["point"] = "CENTER",
["x"] = 0,
},
["targetCastbar"] = {
["point"] = "CENTER",
["relPoint"] = "CENTER",
},
["boss"] = {
["y"] = 251,
["relPoint"] = "CENTER",
["point"] = "CENTER",
["x"] = 661,
},
},
["bossSpacing"] = 80,
["player"] = {
["visOnlyInstances"] = false,
["visHideNoEnemy"] = false,
["detachedPortraitShape"] = "portrait",
["btbLeftClassColor"] = false,
["portraitSize"] = 0,
["playerCastbarY"] = 0,
["leftTextX"] = 0,
["btbClassIconX"] = 0,
["classPowerStyle"] = "none",
["combatIndicatorY"] = 0,
["showInRaid"] = true,
["castSpellNameSize"] = 11,
["healthBarTexture"] = "melli",
["raidMarkerSize"] = 28,
["centerTextX"] = 0,
["visHideMounted"] = false,
["detachedPortraitBorderOpacity"] = 100,
["visHideNoTarget"] = false,
["raidMarkerAlign"] = "right",
["classPowerCustomColor"] = {
["b"] = 0,
["g"] = 0.82,
["r"] = 1,
},
["btbY"] = 0,
["leftTextY"] = 0,
["raidMarkerY"] = 0,
["healthHeight"] = 46,
["healthTextPosition"] = "right",
["playerCastbarHeight"] = 0,
["powerPercentTextPowerColor"] = false,
["btbCenterY"] = 0,
["maxBuffs"] = 4,
["rightTextContent"] = "both",
["raidMarkerEnabled"] = false,
["classPowerEmptyColor"] = {
["a"] = 1,
["b"] = 0.2,
["g"] = 0.2,
["r"] = 0.2,
},
["powerWidth"] = 0,
["btbCenterClassColor"] = false,
["btbLeftX"] = 0,
["centerTextSize"] = 12,
["buffOffsetX"] = 0,
["barVisibility"] = "always",
["debuffAnchor"] = "topright",
["debuffOffsetY"] = 0,
["frameWidth"] = 181,
["buffGrowth"] = "auto",
["classPowerPosition"] = "top",
["buffOffsetY"] = 0,
["borderSize"] = 0,
["healthBarOpacity"] = 90,
["combatIndicatorStyle"] = "class",
["powerX"] = 0,
["rightTextY"] = 0,
["rightTextX"] = 0,
["combatIndicatorSize"] = 22,
["castbarFillColor"] = {
["b"] = 0.639,
["g"] = 0.82,
["r"] = 0.863,
},
["detachedPortraitBorderSize"] = 7,
["powerShowPercent"] = true,
["classThemeStyle"] = "modern",
["showClassPowerBar"] = false,
["playerCastbarX"] = 0,
["btbX"] = 0,
["btbRightContent"] = "none",
["portraitX"] = 0,
["highlightAlpha"] = 1,
["powerPercentY"] = 0,
["borderColor"] = {
["b"] = 0,
["g"] = 0,
["r"] = 0,
},
["classPowerBgColor"] = {
["a"] = 1,
["b"] = 0.082,
["g"] = 0.082,
["r"] = 0.082,
},
["lockClassPowerToFrame"] = true,
["borderAlpha"] = 1,
["classPowerSize"] = 8,
["combatIndicatorPosition"] = "healthbar",
["castDurationColor"] = {
["b"] = 1,
["g"] = 1,
["r"] = 1,
},
["bottomTextBar"] = false,
["debuffGrowth"] = "auto",
["leftTextContent"] = "name",
["powerPercentText"] = "none",
["powerPosition"] = "below",
["powerHeight"] = 6,
["combatIndicatorX"] = 0,
["btbCenterSize"] = 11,
["btbBgOpacity"] = 1,
["classPowerBarY"] = 0,
["btbPosition"] = "bottom",
["powerPercentPowerColor"] = true,
["buffAnchor"] = "none",
["detachedPortraitClassColor"] = true,
["btbRightPowerColor"] = false,
["castSpellNameColor"] = {
["b"] = 1,
["g"] = 1,
["r"] = 1,
},
["btbCenterPowerColor"] = false,
["btbLeftContent"] = "none",
["btbWidth"] = 0,
["btbRightClassColor"] = false,
["showInParty"] = true,
["healthDisplay"] = "both",
["buffSize"] = 22,
["btbRightX"] = 0,
["showSolo"] = true,
["combatIndicatorColor"] = "custom",
["btbRightSize"] = 11,
["textSize"] = 12,
["rightTextSize"] = 12,
["btbClassIconSize"] = 14,
["debuffOffsetX"] = 0,
["maxDebuffs"] = 10,
["powerY"] = -4,
["btbClassIconLocation"] = "left",
["leftTextClassColor"] = false,
["btbRightY"] = 0,
["detachedPortraitBorder"] = true,
["btbCenterX"] = 0,
["classPowerSpacing"] = 2,
["btbLeftSize"] = 11,
["leftTextSize"] = 12,
["powerBarOpacity"] = 100,
["rightTextClassColor"] = false,
["castbarClassColored"] = false,
["centerTextClassColor"] = false,
["castDurationSize"] = 11,
["bottomTextBarHeight"] = 16,
["centerTextY"] = 0,
["highlightColor"] = {
["r"] = 0,
["g"] = 0,
["b"] = 0,
},
["classPowerBarX"] = 0,
["powerPercentX"] = 0,
["raidMarkerX"] = 0,
["debuffSize"] = 22,
["showBuffs"] = false,
["namePosition"] = "left",
["showPlayerCastIcon"] = true,
["powerPercentSize"] = 9,
["powerTextFormat"] = "perpp",
["visHideHousing"] = false,
["healthClassColored"] = true,
["btbLeftPowerColor"] = false,
["showPortrait"] = true,
["btbClassIconY"] = 0,
["castbarHideWhenInactive"] = true,
["lockCastbarToFrame"] = true,
["playerCastbarWidth"] = 0,
["btbCenterContent"] = "none",
["showPlayerAbsorb"] = false,
["detachedPortraitBorderColor"] = {
["b"] = 0,
["g"] = 0,
["r"] = 0,
},
["portraitY"] = 0,
["portraitSide"] = "left",
["portraitMode"] = "2d",
["showPlayerCastbar"] = false,
["btbClassIcon"] = "none",
["classPowerClassColor"] = true,
["btbLeftY"] = 0,
["btbBgColor"] = {
["b"] = 0.2,
["g"] = 0.2,
["r"] = 0.2,
},
["centerTextContent"] = "none",
["customBgColor"] = {
["b"] = 0.067,
["g"] = 0.067,
["r"] = 0.067,
},
["combatIndicatorCustomColor"] = {
["b"] = 1,
["g"] = 1,
["r"] = 1,
},
},
["portraitStyle"] = "attached",
["pet"] = {
["highlightColor"] = {
["b"] = 1,
["g"] = 1,
["r"] = 1,
},
["centerTextContent"] = "none",
["healthHeight"] = 25,
["powerPosition"] = "none",
["portraitMode"] = "2d",
["rightTextContent"] = "none",
["leftTextContent"] = "name",
["textSize"] = 12,
["borderSize"] = 1,
["healthBarOpacity"] = 90,
["borderColor"] = {
["b"] = 0,
["g"] = 0,
["r"] = 0,
},
["healthBarTexture"] = "none",
["showPortrait"] = false,
["customBgColor"] = {
["b"] = 0.067,
["g"] = 0.067,
["r"] = 0.067,
},
["frameWidth"] = 101,
},
["castbarColor"] = {
["b"] = 0.514,
["g"] = 0.655,
["r"] = 0.114,
},
["totPet"] = {
["highlightColor"] = {
["b"] = 1,
["g"] = 1,
["r"] = 1,
},
["centerTextContent"] = "none",
["healthHeight"] = 40,
["powerPosition"] = "none",
["portraitMode"] = "2d",
["rightTextContent"] = "none",
["leftTextContent"] = "name",
["textSize"] = 12,
["borderSize"] = 1,
["healthBarOpacity"] = 90,
["borderColor"] = {
["b"] = 0,
["g"] = 0,
["r"] = 0,
},
["healthBarTexture"] = "none",
["showPortrait"] = false,
["customBgColor"] = {
["b"] = 0.067,
["g"] = 0.067,
["r"] = 0.067,
},
["frameWidth"] = 101,
},
["playerTarget"] = {
["onlyPlayerDebuffs"] = false,
["buffSize"] = 22,
["playerCastbarY"] = 0,
["castbarHeight"] = 14,
["buffOffsetX"] = 0,
["powerY"] = -4,
["debuffOffsetY"] = 0,
["frameWidth"] = 181,
["powerPercentText"] = "none",
["playerCastbarWidth"] = 0,
["debuffSize"] = 22,
["showBuffs"] = true,
["maxDebuffs"] = 20,
["powerHeight"] = 6,
["buffOffsetY"] = 0,
["debuffOffsetX"] = 0,
["powerTextFormat"] = "perpp",
["powerPercentSize"] = 9,
["powerPercentX"] = 0,
["powerPercentPowerColor"] = true,
["healthHeight"] = 46,
["powerPercentY"] = 0,
["classPowerBarY"] = 0,
["playerCastbarHeight"] = 0,
["maxBuffs"] = 4,
["powerShowPercent"] = true,
["healthDisplay"] = "both",
["showClassPowerBar"] = false,
["playerCastbarX"] = 0,
["classPowerBarX"] = 0,
["showPlayerCastbar"] = false,
["powerPercentTextPowerColor"] = false,
["showPlayerAbsorb"] = false,
["healthClassColored"] = true,
},
["boss"] = {
["raidMarkerEnabled"] = true,
["onlyPlayerDebuffs"] = true,
["castbarHideWhenInactive"] = false,
["buffSize"] = 22,
["powerWidth"] = 0,
["powerPercentY"] = 0,
["borderColor"] = {
["b"] = 0,
["g"] = 0,
["r"] = 0,
},
["castbarHeight"] = 14,
["rightTextContent"] = "perhp",
["textSize"] = 12,
["buffOffsetX"] = 0,
["powerY"] = -4,
["frameWidth"] = 160,
["powerPercentText"] = "none",
["buffGrowth"] = "auto",
["maxDebuffs"] = 10,
["portraitMode"] = "2d",
["castDurationColor"] = {
["b"] = 1,
["g"] = 1,
["r"] = 1,
},
["castDurationSize"] = 11,
["borderSize"] = 1,
["powerBarOpacity"] = 100,
["debuffOffsetY"] = 0,
["powerPercentTextPowerColor"] = false,
["debuffGrowth"] = "auto",
["castSpellNameSize"] = 11,
["leftTextContent"] = "name",
["raidMarkerSize"] = 28,
["highlightColor"] = {
["b"] = 1,
["g"] = 1,
["r"] = 1,
},
["raidMarkerY"] = 0,
["centerTextContent"] = "none",
["raidMarkerX"] = 0,
["debuffSize"] = 22,
["showBuffs"] = false,
["raidMarkerAlign"] = "left",
["powerHeight"] = 6,
["buffOffsetY"] = 0,
["showCastIcon"] = true,
["showCastbar"] = true,
["healthClassColored"] = true,
["powerPercentSize"] = 9,
["showPortrait"] = false,
["powerPercentX"] = 0,
["powerPercentPowerColor"] = true,
["buffAnchor"] = "topleft",
["powerX"] = 0,
["healthHeight"] = 34,
["debuffOffsetX"] = 0,
["healthBarOpacity"] = 90,
["castbarFillColor"] = {
["b"] = 0.639,
["g"] = 0.82,
["r"] = 0.863,
},
["castSpellNameColor"] = {
["b"] = 1,
["g"] = 1,
["r"] = 1,
},
["powerShowPercent"] = true,
["healthDisplay"] = "perhp",
["powerTextFormat"] = "perpp",
["maxBuffs"] = 4,
["powerPosition"] = "below",
["healthBarTexture"] = "none",
["debuffAnchor"] = "bottomleft",
["customBgColor"] = {
["b"] = 0.067,
["g"] = 0.067,
["r"] = 0.067,
},
["castbarClassColored"] = false,
},
["focus"] = {
["visHideHousing"] = false,
["onlyPlayerDebuffs"] = true,
["castbarHideWhenInactive"] = true,
["detachedPortraitShape"] = "portrait",
["portraitX"] = 0,
["btbLeftClassColor"] = false,
["portraitSize"] = 0,
["powerPercentY"] = 0,
["borderColor"] = {
["b"] = 0,
["g"] = 0,
["r"] = 0,
},
["leftTextX"] = 0,
["castbarHeight"] = 14,
["btbClassIconX"] = 0,
["castbarClassColored"] = false,
["visOnlyInstances"] = false,
["btbRightContent"] = "none",
["leftTextSize"] = 12,
["rightTextClassColor"] = false,
["castDurationColor"] = {
["b"] = 1,
["g"] = 1,
["r"] = 1,
},
["showInRaid"] = true,
["castDurationSize"] = 11,
["raidMarkerSize"] = 28,
["bottomTextBar"] = false,
["btbCenterX"] = 0,
["debuffGrowth"] = "auto",
["castSpellNameSize"] = 11,
["leftTextContent"] = "name",
["powerPercentText"] = "none",
["centerTextX"] = 0,
["visHideMounted"] = false,
["debuffOffsetX"] = 0,
["powerPosition"] = "below",
["castbarWidth"] = 200,
["leftTextY"] = 0,
["raidMarkerAlign"] = "right",
["powerHeight"] = 6,
["buffAnchor"] = "topleft",
["showCastIcon"] = true,
["btbCenterSize"] = 11,
["btbBgOpacity"] = 1,
["btbY"] = 0,
["btbPosition"] = "bottom",
["showSolo"] = true,
["powerPercentPowerColor"] = true,
["raidMarkerY"] = 0,
["powerPercentTextPowerColor"] = false,
["healthHeight"] = 34,
["detachedPortraitClassColor"] = true,
["btbRightPowerColor"] = false,
["maxDebuffs"] = 10,
["castSpellNameColor"] = {
["b"] = 1,
["g"] = 1,
["r"] = 1,
},
["healthBarTexture"] = "none",
["healthDisplay"] = "perhp",
["btbCenterPowerColor"] = false,
["maxBuffs"] = 4,
["btbWidth"] = 0,
["btbLeftContent"] = "none",
["powerX"] = 0,
["rightTextContent"] = "perhp",
["btbRightX"] = 0,
["raidMarkerEnabled"] = false,
["centerTextSize"] = 12,
["btbClassIconY"] = 0,
["btbRightClassColor"] = false,
["detachedPortraitBorder"] = true,
["powerPercentSize"] = 9,
["buffSize"] = 22,
["btbCenterContent"] = "none",
["btbCenterClassColor"] = false,
["btbLeftX"] = 0,
["btbRightSize"] = 11,
["healthBarOpacity"] = 90,
["rightTextSize"] = 12,
["btbClassIconSize"] = 14,
["textSize"] = 12,
["showInParty"] = true,
["powerY"] = -4,
["debuffAnchor"] = "bottomleft",
["leftTextClassColor"] = false,
["btbRightY"] = 0,
["barVisibility"] = "always",
["portraitMode"] = "2d",
["btbClassIcon"] = "none",
["btbLeftSize"] = 11,
["btbBgColor"] = {
["b"] = 0.2,
["g"] = 0.2,
["r"] = 0.2,
},
["powerBarOpacity"] = 100,
["debuffOffsetY"] = 0,
["btbLeftY"] = 0,
["frameWidth"] = 160,
["highlightColor"] = {
["b"] = 1,
["g"] = 1,
["r"] = 1,
},
["bottomTextBarHeight"] = 16,
["centerTextY"] = 0,
["buffGrowth"] = "auto",
["detachedPortraitBorderColor"] = {
["b"] = 0,
["g"] = 0,
["r"] = 0,
},
["portraitY"] = 0,
["raidMarkerX"] = 0,
["debuffSize"] = 22,
["showBuffs"] = false,
["detachedPortraitBorderOpacity"] = 100,
["buffOffsetX"] = 0,
["buffOffsetY"] = 0,
["borderSize"] = 1,
["showCastbar"] = true,
["healthClassColored"] = true,
["btbLeftPowerColor"] = false,
["showPortrait"] = true,
["powerPercentX"] = 0,
["powerTextFormat"] = "perpp",
["powerWidth"] = 0,
["centerTextContent"] = "none",
["rightTextY"] = 0,
["rightTextX"] = 0,
["btbCenterY"] = 0,
["castbarFillColor"] = {
["b"] = 0.639,
["g"] = 0.82,
["r"] = 0.863,
},
["detachedPortraitBorderSize"] = 7,
["powerShowPercent"] = true,
["classThemeStyle"] = "modern",
["btbClassIconLocation"] = "left",
["visHideNoTarget"] = false,
["portraitSide"] = "right",
["visHideNoEnemy"] = false,
["btbX"] = 0,
["customBgColor"] = {
["b"] = 0.067,
["g"] = 0.067,
["r"] = 0.067,
},
["centerTextClassColor"] = false,
},
["target"] = {
["visOnlyInstances"] = false,
["onlyPlayerDebuffs"] = false,
["castbarHideWhenInactive"] = true,
["detachedPortraitShape"] = "portrait",
["portraitX"] = 0,
["btbLeftClassColor"] = false,
["portraitSize"] = 0,
["powerPercentY"] = 0,
["borderColor"] = {
["b"] = 0,
["g"] = 0,
["r"] = 0,
},
["visHideHousing"] = false,
["leftTextX"] = 0,
["castbarHeight"] = 14,
["btbClassIconX"] = 0,
["castbarClassColored"] = false,
["btbRightContent"] = "none",
["leftTextSize"] = 12,
["visHideNoEnemy"] = false,
["showInRaid"] = true,
["rightTextClassColor"] = false,
["castDurationColor"] = {
["b"] = 1,
["g"] = 1,
["r"] = 1,
},
["castDurationSize"] = 11,
["powerPercentText"] = "none",
["visHideNoTarget"] = false,
["bottomTextBar"] = false,
["raidMarkerAlign"] = "right",
["debuffGrowth"] = "auto",
["castSpellNameSize"] = 11,
["leftTextContent"] = "name",
["raidMarkerSize"] = 28,
["centerTextX"] = 0,
["visHideMounted"] = false,
["btbLeftY"] = 0,
["powerPosition"] = "below",
["castbarWidth"] = 233,
["buffAnchor"] = "topleft",
["maxDebuffs"] = 20,
["powerHeight"] = 6,
["healthTextPosition"] = "right",
["showCastIcon"] = true,
["debuffOffsetX"] = 0,
["btbBgOpacity"] = 1,
["btbY"] = 0,
["btbPosition"] = "bottom",
["raidMarkerEnabled"] = false,
["leftTextY"] = 0,
["raidMarkerY"] = 0,
["powerPercentTextPowerColor"] = false,
["healthHeight"] = 46,
["detachedPortraitClassColor"] = true,
["btbRightPowerColor"] = false,
["showSolo"] = true,
["castSpellNameColor"] = {
["b"] = 1,
["g"] = 1,
["r"] = 1,
},
["powerX"] = 0,
["healthDisplay"] = "both",
["btbCenterY"] = 0,
["maxBuffs"] = 4,
["powerTextFormat"] = "perpp",
["btbLeftContent"] = "none",
["powerWidth"] = 0,
["rightTextContent"] = "both",
["btbClassIconY"] = 0,
["btbWidth"] = 0,
["centerTextSize"] = 12,
["powerPercentSize"] = 9,
["btbRightClassColor"] = false,
["healthBarOpacity"] = 90,
["showInParty"] = true,
["buffSize"] = 22,
["btbRightX"] = 0,
["btbCenterClassColor"] = false,
["btbLeftX"] = 0,
["btbRightSize"] = 11,
["barVisibility"] = "always",
["portraitY"] = 0,
["btbClassIconSize"] = 14,
["textSize"] = 12,
["buffOffsetX"] = 0,
["powerY"] = -4,
["debuffAnchor"] = "bottomleft",
["leftTextClassColor"] = false,
["btbRightY"] = 0,
["detachedPortraitBorder"] = true,
["portraitMode"] = "2d",
["detachedPortraitBorderColor"] = {
["b"] = 0,
["g"] = 0,
["r"] = 0,
},
["btbLeftSize"] = 11,
["btbClassIcon"] = "none",
["powerBarOpacity"] = 100,
["debuffOffsetY"] = 0,
["btbCenterPowerColor"] = false,
["btbCenterSize"] = 11,
["bottomTextBarHeight"] = 16,
["frameWidth"] = 181,
["highlightColor"] = {
["b"] = 1,
["g"] = 1,
["r"] = 1,
},
["buffGrowth"] = "auto",
["btbCenterX"] = 0,
["centerTextY"] = 0,
["raidMarkerX"] = 0,
["debuffSize"] = 22,
["showBuffs"] = true,
["namePosition"] = "left",
["btbClassIconLocation"] = "left",
["buffOffsetY"] = 0,
["borderSize"] = 1,
["showCastbar"] = true,
["healthClassColored"] = true,
["btbLeftPowerColor"] = false,
["showPortrait"] = true,
["powerPercentX"] = 0,
["rightTextSize"] = 12,
["btbCenterContent"] = "none",
["centerTextContent"] = "none",
["rightTextY"] = 0,
["rightTextX"] = 0,
["btbBgColor"] = {
["b"] = 0.2,
["g"] = 0.2,
["r"] = 0.2,
},
["castbarFillColor"] = {
["b"] = 0.639,
["g"] = 0.82,
["r"] = 0.863,
},
["detachedPortraitBorderSize"] = 7,
["powerShowPercent"] = true,
["classThemeStyle"] = "modern",
["powerPercentPowerColor"] = true,
["detachedPortraitBorderOpacity"] = 100,
["portraitSide"] = "right",
["healthBarTexture"] = "none",
["btbX"] = 0,
["customBgColor"] = {
["b"] = 0.067,
["g"] = 0.067,
["r"] = 0.067,
},
["centerTextClassColor"] = false,
},
["darkTheme"] = false,
["healthBarTexture"] = "none",
["portraitMode"] = "2d",
},
["EllesmereUICooldownManager"] = {
["cdmBarPositions"] = {
["cooldowns"] = {
["y"] = -196.7689819335938,
["relPoint"] = "CENTER",
["point"] = "CENTER",
["x"] = -17.97433471679688,
},
["buffs"] = {
["point"] = "CENTER",
["relPoint"] = "CENTER",
},
["utility"] = {
["point"] = "CENTER",
["relPoint"] = "CENTER",
},
},
["cdmBars"] = {
["enabled"] = true,
["hideBuffsWhenInactive"] = true,
["useBlizzardBuffBars"] = false,
["rotationHelperGlowStyle"] = 5,
["bars"] = {
{
["visHideHousing"] = true,
["borderThickness"] = "thin",
["keybindB"] = 1,
["outOfRangeOverlay"] = true,
["numRows"] = 1,
["borderA"] = 1,
["key"] = "cooldowns",
["keybindOffsetX"] = 2,
["anchorOffsetY"] = 0,
["enabled"] = true,
["keybindA"] = 0.9,
["anchorPosition"] = "left",
["barBgB"] = 0,
["name"] = "Cooldowns",
["borderG"] = 0,
["anchorOffsetX"] = 0,
["barType"] = "cooldowns",
["visHideMounted"] = false,
["anchorTo"] = "none",
["pandemicGlow"] = true,
["borderClassColor"] = true,
["borderB"] = 0,
["activeStateAnim"] = "3",
["visHideNoTarget"] = false,
["pandemicGlowStyle"] = 3,
["iconShape"] = "none",
["borderR"] = 0,
["spacing"] = 0,
["borderSize"] = 1,
["keybindR"] = 1,
["bgB"] = 0.08,
["iconSize"] = 45,
["barBgEnabled"] = false,
["visOnlyInstances"] = false,
["showCooldownText"] = true,
["bgA"] = 0.6,
["verticalOrientation"] = false,
["showTooltip"] = false,
["visHideNoEnemy"] = false,
["keybindOffsetY"] = -2,
["pandemicGlowColor"] = {
["r"] = 0.9699978110194052,
},
["housingHideEnabled"] = true,
["keybindSize"] = 10,
["keybindG"] = 1,
["barBgR"] = 0,
["iconZoom"] = 0.08,
["bgG"] = 0.08,
["barBgG"] = 0,
["bgR"] = 0.08,
["showKeybind"] = false,
["barVisibility"] = "always",
},
{
["visHideHousing"] = true,
["borderThickness"] = "thin",
["keybindB"] = 1,
["numRows"] = 1,
["borderA"] = 1,
["key"] = "utility",
["keybindOffsetX"] = 2,
["anchorOffsetY"] = 0,
["enabled"] = true,
["keybindA"] = 0.9,
["name"] = "Utility",
["borderG"] = 0,
["barType"] = "utility",
["bgR"] = 0.08,
["anchorOffsetX"] = 0,
["visHideMounted"] = false,
["borderB"] = 0,
["anchorTo"] = "none",
["visHideNoTarget"] = false,
["barBgEnabled"] = false,
["barBgB"] = 0,
["keybindR"] = 1,
["spacing"] = 0,
["borderSize"] = 1,
["borderR"] = 0,
["bgB"] = 0.08,
["iconSize"] = 38,
["borderClassColor"] = true,
["iconShape"] = "none",
["showCooldownText"] = true,
["bgA"] = 0.6,
["verticalOrientation"] = false,
["showTooltip"] = false,
["visHideNoEnemy"] = false,
["keybindOffsetY"] = -2,
["visOnlyInstances"] = false,
["housingHideEnabled"] = true,
["keybindSize"] = 10,
["anchorPosition"] = "left",
["barBgR"] = 0,
["iconZoom"] = 0.08,
["bgG"] = 0.08,
["barBgG"] = 0,
["keybindG"] = 1,
["showKeybind"] = false,
["barVisibility"] = "always",
},
{
["visHideHousing"] = true,
["borderThickness"] = "thin",
["keybindB"] = 1,
["numRows"] = 1,
["borderA"] = 1,
["key"] = "buffs",
["keybindOffsetX"] = 2,
["anchorOffsetY"] = 0,
["enabled"] = true,
["keybindA"] = 0.9,
["name"] = "Buffs",
["borderG"] = 0,
["barType"] = "buffs",
["barBgEnabled"] = true,
["bgR"] = 0.08,
["visHideMounted"] = false,
["borderB"] = 0,
["anchorTo"] = "none",
["visHideNoTarget"] = false,
["anchorOffsetX"] = 0,
["barBgB"] = 0,
["keybindR"] = 1,
["spacing"] = 2,
["borderSize"] = 1,
["borderR"] = 0,
["bgB"] = 0.08,
["iconSize"] = 25,
["borderClassColor"] = true,
["iconShape"] = "none",
["showCooldownText"] = true,
["bgA"] = 0.6,
["verticalOrientation"] = false,
["showTooltip"] = false,
["visHideNoEnemy"] = false,
["keybindOffsetY"] = -2,
["visOnlyInstances"] = false,
["housingHideEnabled"] = true,
["keybindSize"] = 10,
["anchorPosition"] = "left",
["barBgR"] = 0,
["iconZoom"] = 0.08,
["bgG"] = 0.08,
["barBgG"] = 0,
["keybindG"] = 1,
["showKeybind"] = false,
["barVisibility"] = "always",
},
{
["anchorPosition"] = "left",
["focusCastSoundKey"] = "none",
["outOfRangeOverlay"] = false,
["numRows"] = 1,
["borderA"] = 1,
["key"] = "focuskick",
["swipeAlpha"] = 0.7,
["anchorOffsetY"] = 0,
["enabled"] = true,
["focusReminderSize"] = 26,
["focusReminderB"] = 1,
["barVisibility"] = "always",
["cooldownFontSize"] = 12,
["stackCountSize"] = 11,
["barBgEnabled"] = false,
["desaturateOnCD"] = true,
["name"] = "FocusKick",
["borderG"] = 0,
["barBgB"] = 0,
["barType"] = "cooldowns",
["borderThickness"] = "thin",
["anchorTo"] = "none",
["pandemicGlow"] = false,
["borderClassColor"] = false,
["borderB"] = 0,
["activeStateAnim"] = "blizzard",
["bgR"] = 0.08,
["bgB"] = 0.08,
["barBgR"] = 0,
["growDirection"] = "RIGHT",
["focusReminderEnabled"] = false,
["borderSize"] = 1,
["borderR"] = 0,
["spacing"] = 2,
["iconSize"] = 28,
["showCharges"] = true,
["anchorOffsetX"] = 0,
["showCooldownText"] = true,
["bgA"] = 0.6,
["verticalOrientation"] = false,
["focusReminderOffsetX"] = 0,
["focusReminderG"] = 1,
["focusReminderR"] = 1,
["showStackCount"] = false,
["focusReminderOffsetY"] = 0,
["focusReminderUseAccent"] = true,
["nameplateOffsetX"] = 0,
["iconShape"] = "none",
["iconZoom"] = 0.08,
["bgG"] = 0.08,
["barBgG"] = 0,
["nameplateAnchorSide"] = "LEFT",
["chargeFontSize"] = 11,
["nameplateOffsetY"] = 0,
},
{
["enabled"] = true,
["barVisibility"] = "never",
["numRows"] = 1,
["growDirection"] = "RIGHT",
["name"] = "Hidden CDs",
["spacing"] = 0,
["iconSize"] = 1,
["barType"] = "cooldowns",
["key"] = "__ghost_cd",
["isGhostBar"] = true,
},
{
["enabled"] = true,
["barVisibility"] = "never",
["numRows"] = 1,
["iconSize"] = 1,
["key"] = "__ghost_buffs",
["spacing"] = 0,
["isGhostBar"] = true,
["barType"] = "buffs",
["growDirection"] = "RIGHT",
["name"] = "Hidden Buffs",
},
},
["rotationHelperEnabled"] = false,
["hideBlizzard"] = true,
},
["activeSpecKey"] = "0",
["reskinBorders"] = true,
["spec"] = {
["255"] = {
["mappings"] = {
{
["enabled"] = false,
["actionButton"] = 1,
["cdmSlot"] = 1,
["actionBar"] = 1,
["glowColor"] = {
["r"] = 1,
["g"] = 0.82,
["b"] = 0.1,
},
["name"] = "Buff Name (eg: Divine Purpose)",
["mode"] = "ACTIVE",
["glowStyle"] = 1,
["hideFromCDM"] = false,
},
},
["selectedMapping"] = 1,
},
["260"] = {
["mappings"] = {
{
["enabled"] = false,
["actionButton"] = 1,
["cdmSlot"] = 1,
["actionBar"] = 1,
["glowColor"] = {
["b"] = 0.1,
["g"] = 0.82,
["r"] = 1,
},
["name"] = "Buff Name (eg: Divine Purpose)",
["mode"] = "ACTIVE",
["glowStyle"] = 1,
["hideFromCDM"] = false,
},
},
["selectedMapping"] = 1,
},
["581"] = {
["mappings"] = {
{
["enabled"] = false,
["actionButton"] = 1,
["cdmSlot"] = 1,
["actionBar"] = 1,
["glowColor"] = {
["r"] = 1,
["g"] = 0.82,
["b"] = 0.1,
},
["name"] = "Buff Name (eg: Divine Purpose)",
["mode"] = "ACTIVE",
["glowStyle"] = 1,
["hideFromCDM"] = false,
},
},
["selectedMapping"] = 1,
},
["1449"] = {
["mappings"] = {
{
["enabled"] = false,
["actionButton"] = 1,
["cdmSlot"] = 1,
["actionBar"] = 1,
["glowColor"] = {
["r"] = 1,
["g"] = 0.82,
["b"] = 0.1,
},
["name"] = "Buff Name (eg: Divine Purpose)",
["mode"] = "ACTIVE",
["glowStyle"] = 1,
["hideFromCDM"] = false,
},
},
["selectedMapping"] = 1,
},
["1480"] = {
["mappings"] = {
{
["enabled"] = false,
["actionButton"] = 1,
["cdmSlot"] = 1,
["actionBar"] = 1,
["glowColor"] = {
["b"] = 0.1,
["g"] = 0.82,
["r"] = 1,
},
["name"] = "Buff Name (eg: Divine Purpose)",
["mode"] = "ACTIVE",
["glowStyle"] = 1,
["hideFromCDM"] = false,
},
},
["selectedMapping"] = 1,
},
["1467"] = {
["mappings"] = {
{
["enabled"] = false,
["actionButton"] = 1,
["cdmSlot"] = 1,
["actionBar"] = 1,
["glowColor"] = {
["r"] = 1,
["g"] = 0.82,
["b"] = 0.1,
},
["name"] = "Buff Name (eg: Divine Purpose)",
["mode"] = "ACTIVE",
["glowStyle"] = 1,
["hideFromCDM"] = false,
},
},
["selectedMapping"] = 1,
},
["577"] = {
["mappings"] = {
},
["selectedMapping"] = 1,
},
},
},
["EllesmereUIResourceBars"] = {
["castBar"] = {
["lastTickG"] = 0.82,
["showLastTick"] = false,
["gradientEnabled"] = true,
["gcdBoundaryR"] = 1,
["borderA"] = 1,
["classColored"] = false,
["enabled"] = true,
["spellTextSize"] = 11,
["gradientG"] = 0.2,
["gcdBoundaryG"] = 0.82,
["unlockPos"] = {
["y"] = -140.1537475585938,
["relPoint"] = "CENTER",
["point"] = "CENTER",
["x"] = -4.71795654296875,
},
["gradientA"] = 1,
["anchorX"] = 0,
["fillB"] = 1,
["height"] = 20,
["lastTickA"] = 0.95,
["fillR"] = 0.5961499619342367,
["borderG"] = 0,
["gcdBoundaryA"] = 0.95,
["bgG"] = 0,
["tickMarksR"] = 1,
["anchorY"] = -54,
["bgR"] = 0,
["showSpellText"] = true,
["borderB"] = 1,
["showTickMarks"] = true,
["showTimer"] = true,
["tickMarksB"] = 1,
["showSpark"] = true,
["borderSize"] = 2,
["timerY"] = 0,
["gcdBoundaryB"] = 0,
["borderR"] = 0.4484620946399094,
["spellTextY"] = 0,
["showChannelTicks"] = true,
["showIcon"] = true,
["tickMarksG"] = 1,
["texture"] = "none",
["bgA"] = 0.7,
["showGCDBoundary"] = false,
["spellTextX"] = 0,
["gradientR"] = 0.2,
["tickMarksA"] = 0.7,
["lastTickR"] = 1,
["timerSize"] = 11,
["width"] = 220,
["coloredEmpowerStages"] = false,
["bgB"] = 0,
["timerX"] = 0,
["fillA"] = 1,
["gradientDir"] = "HORIZONTAL",
["gradientB"] = 0.8,
["lastTickB"] = 0,
["fillG"] = 0,
},
["general"] = {
["orientation"] = "HORIZONTAL",
["barTexture"] = "sm:Solid",
["anchorX"] = 0,
["anchorY"] = -100,
},
["primary"] = {
["thresholdEnabled"] = true,
["visHideNoEnemy"] = false,
["textYOffset"] = 0,
["customColored"] = false,
["borderA"] = 1,
["offsetX"] = 0,
["showPercent"] = true,
["darkTheme"] = false,
["textSize"] = 10,
["enabled"] = true,
["textFormat"] = "smart",
["thresholdR"] = 1,
["thresholdA"] = 1,
["fillB"] = 0.24,
["expandIfNoResource"] = false,
["unlockPos"] = {
["y"] = -228.9229431152344,
["relPoint"] = "CENTER",
["point"] = "CENTER",
["x"] = 3.0517578125e-05,
},
["borderG"] = 0,
["height"] = 20,
["offsetY"] = -54,
["thresholdPartialOnly"] = true,
["bgR"] = 0.06666666666666667,
["visHideMounted"] = false,
["borderB"] = 0,
["visHideNoTarget"] = false,
["borderSize"] = 2,
["borderR"] = 0,
["bgB"] = 0.06666666666666667,
["bgA"] = 0.75,
["thresholdPct"] = 84,
["thresholdB"] = 0.2,
["visibility"] = "always",
["fillR"] = 0.77,
["fillA"] = 1,
["width"] = 214,
["visHideHousing"] = false,
["thresholdG"] = 0.2,
["visOnlyInstances"] = false,
["bgG"] = 0.06666666666666667,
["orientation"] = "HORIZONTAL",
["textXOffset"] = 0,
["barAlpha"] = 1,
["fillG"] = 0.53,
},
["health"] = {
["thresholdEnabled"] = false,
["visHideNoEnemy"] = false,
["textYOffset"] = 0,
["customColored"] = false,
["borderA"] = 1,
["offsetX"] = 0,
["darkTheme"] = false,
["textSize"] = 11,
["enabled"] = false,
["textFormat"] = "none",
["thresholdR"] = 1,
["thresholdA"] = 1,
["fillB"] = 0.45,
["thresholdB"] = 0.2,
["borderG"] = 0,
["height"] = 20,
["offsetY"] = -64,
["barAlpha"] = 1,
["bgR"] = 0.06666666666666667,
["visHideMounted"] = false,
["borderB"] = 0,
["visHideNoTarget"] = false,
["borderSize"] = 2,
["borderR"] = 0,
["bgB"] = 0.06666666666666667,
["bgA"] = 0.75,
["thresholdPct"] = 30,
["thresholdG"] = 0.2,
["visibility"] = "always",
["width"] = 214,
["fillR"] = 0.67,
["fillA"] = 1,
["visOnlyInstances"] = false,
["bgG"] = 0.06666666666666667,
["orientation"] = "HORIZONTAL",
["textXOffset"] = 0,
["visHideHousing"] = false,
["fillG"] = 0.83,
},
["secondary"] = {
["thresholdEnabled"] = false,
["visHideNoEnemy"] = false,
["textYOffset"] = 0,
["barBgA"] = 0.5,
["borderA"] = 1,
["oocAlpha"] = 1,
["classColored"] = true,
["darkTheme"] = false,
["textSize"] = 11,
["enabled"] = true,
["thresholdR"] = 0.04705882352941176,
["thresholdA"] = 1,
["fillB"] = 1,
["unlockPos"] = {
["y"] = -248.6153259277344,
["relPoint"] = "CENTER",
["point"] = "CENTER",
["x"] = -3.0517578125e-05,
},
["showText"] = true,
["borderG"] = 0,
["tickValues"] = "",
["barAlpha"] = 1,
["chargedG"] = 0,
["bgR"] = 1,
["visHideMounted"] = false,
["borderB"] = 0,
["thresholdB"] = 0.615686274509804,
["pipSpacing"] = 1,
["chargedR"] = 0.5561560961480803,
["fillR"] = 0.580771050989286,
["bgG"] = 1,
["pipOrientation"] = "HORIZONTAL",
["borderSize"] = 2,
["borderR"] = 0,
["bgB"] = 1,
["thresholdCount"] = 63,
["thresholdG"] = 0.8235294117647058,
["offsetX"] = 0,
["pipHeight"] = 20,
["bgA"] = 0.1,
["barBgB"] = 0,
["visHideNoTarget"] = false,
["pipWidth"] = 214,
["visOnlyInstances"] = false,
["visHideHousing"] = false,
["visibility"] = "always",
["chargedA"] = 1,
["chargedB"] = 1,
["barBgR"] = 0,
["thresholdPartialOnly"] = false,
["fillA"] = 1,
["barBgG"] = 0,
["textXOffset"] = 0,
["offsetY"] = -38,
["fillG"] = 0,
},
},
},
["customColors"] = {
["class"] = {
["DEMONHUNTER"] = {
["b"] = 0.79,
["g"] = 0.19,
["r"] = 0.64,
},
},
},
["_migrations"] = {
["quest_tracker_sec_color_default"] = true,
["cdm_repair_bar_keys_v1"] = true,
["friends_data_wipe_v1"] = true,
["cdm_pandemic_glow_color_table"] = true,
["cdm_active_state_per_bar_to_per_icon"] = true,
["cdm_remove_misc_bars"] = true,
["basics_minimap_round_to_circle"] = true,
["cdm_active_state_anim_none_to_hideactive"] = true,
["eab_round_button_sizes"] = true,
["erb_round_size_fields"] = true,
["basics_minimap_strip_scale"] = true,
["cdm_mouseover_visibility_to_always"] = true,
["basics_minimap_hide_buttons_split"] = true,
},
["unlockLayout"] = {
["anchors"] = {
["Bar3"] = {
["target"] = "MainBar",
["offsetY"] = -5.91278076171875e-05,
["side"] = "LEFT",
["offsetX"] = -11.48724365234375,
},
["CDM_buffs"] = {
["target"] = "CDM_cooldowns",
["offsetY"] = -6.103515625e-05,
["side"] = "TOP",
["offsetX"] = 3.0517578125e-05,
},
["focusCastbar"] = {
["target"] = "focus",
["offsetY"] = 4.57763671875e-05,
["side"] = "BOTTOM",
["offsetX"] = -0.8204345703125,
},
["Bar2"] = {
["target"] = "MainBar",
["offsetY"] = -5.91278076171875e-05,
["side"] = "RIGHT",
["offsetX"] = 11.4871826171875,
},
["CDM_utility"] = {
["target"] = "CDM_cooldowns",
["offsetY"] = -36.10256958007813,
["side"] = "BOTTOM",
["offsetX"] = -3.0517578125e-05,
},
["playerCastbar"] = {
["target"] = "player",
["side"] = "BOTTOM",
},
["targetCastbar"] = {
["target"] = "target",
["offsetY"] = -6.103515625e-05,
["side"] = "BOTTOM",
["offsetX"] = 0.82049560546875,
},
["Bar4"] = {
["target"] = "CDM_cooldowns",
["offsetY"] = 0.4102630615234375,
["side"] = "RIGHT",
["offsetX"] = 0,
},
},
["widthMatch"] = {
["playerCastbar"] = "player",
["targetCastbar"] = "target",
["focusCastbar"] = "focus",
},
["heightMatch"] = {
["Bar4"] = "CDM_cooldowns",
},
["phantomBounds"] = {
},
},
}

    -- Add to profile order so it shows in the UI
    EllesmereUIDB.profileOrder = EllesmereUIDB.profileOrder or {}
    local found = false
    for _, name in ipairs(EllesmereUIDB.profileOrder) do
        if name == PRESET_NAME then found = true; break end
    end
    if not found then
        table.insert(EllesmereUIDB.profileOrder, 1, PRESET_NAME)
    end

    -- If this is a completely fresh install (no active profile), set Bulshack as default
    if not EllesmereUIDB.activeProfile or EllesmereUIDB.activeProfile == "" then
        EllesmereUIDB.activeProfile = PRESET_NAME
    end
end)
